### ISSUE TITLE
limesonline.com not working

### ISSUE THREAD

**Issue by frasty** [massimobedini/riptherep#4]
limesonline.com apparently doesn't bypass the paywall on Chromium 71.0.3578.98:
```
Uncaught TypeError: Cannot read property 'onBeforeRequest' of undefined
    at content_script.js:83
```

**Comment by kanik0** [comment]
Hey there, thank you for opening the issue. I've just pushed an update that should fix this problem ([commit](https://github.com/massimobedini/riptherep/commit/5d6e3cd4aae05b2ee1530acadb328313ecc89ea8)) let me know if it works for you, thanks!

**Comment by frasty** [comment]
That works perfectly, thank you!

**Comment by kanik0** [comment]
Great! Closing the issue
