### ISSUE TITLE
Paywall still visible on Il Tirreno website

### ISSUE THREAD

**Issue by agiovinazzi** [massimobedini/riptherep#7]
The paywall on Il Tirreno website is still visible:

i.e. https://iltirreno.gelocal.it/pontedera/2021/10/02/news/la-lavanderia-industriale-4-0-portera-decine-di-posti-di-lavoro-a-navacchio-1.40766879

**Comment by kanik0** [comment]
It should work now, kindly provide feedback.

**Comment by agiovinazzi** [comment]
It works, thank you
